---
title: "tip_flagging_report"
format: html
editor: visual
---

# TIP Flagging Report

The TIP flagging process has been developed to institute flags in the data entry process of the TIP program. The variables pertaining to length-weight composition were addressed first. This process began with the exploration of the data set by species to visualize the available data by variable. Examples of the figures produced are provided within this document. The flagging process looked at lapses in data collection across variables, accuracy of data collected, and distribution of data collected across time. The flagging scripts employ a fill-in-the-blank method to allow for island and species specific flagging. 

The following is the order in which exploration took place: 
0. preparation 
 - learn the dataset
 - identify key resource documents
1. variable reporting consistency across all islands and species
 - how many variables have 100% or 0% reporting consistencies
 - which variables fluctuate in reporting consistencies and why
   - identify relevant variable for length-weight composition 
 - visualize reporting consistency across time
2. length-weight relevant variable investigation by species
 - data visualization - visually identify outliers in length and weight variables
   - county_sampled over time
   - sample_weight over time by county_sampled
   - gear utilization over time by county_sampled
   - obs_weight over time by county_sampled
   - length over time by county sampled
 - statistical exploration of length values
   - Molly Stevens's SEDAR size-comp script exploration 
   - collaborate with Kyle Dettloff on Generalized Mixed Model Linear analysis of measured lengths relative to gear and time 
3. Quarto document to streamline SEDAR size comp analysis with flags included
4. streamlined scripts of all flagging and visualization completed in this project 

The second aspect of this project was to explore the historical TIP data of Puerto Rico available in ORACLE and compare it to the original records to ensure data quality in the transfers. Though this exploration and 
