---
title: "Historical TIP Flagging by Year"
author: "Katherine Godwin"
format: html
editor: visual
---

#### Load data

```{r}
# run 1.0 script 

# extract oracle by yr and state: 

cr_tip_yr(state_codes = 'PR', year = "1997")

# load ORACLE 
com_tip_PR_1997 <- readRDS("~/SEFSC-SFD-CFB-TIP-Compositions/data/raw/com_tip_PR_1997_20231117.RDS")

# Create a comparable table 
com_tip_PR_1997_skeleton <- com_tip_PR_1997 %>%  # select comparable variables 
  select(ID, INTERVIEW_DATE, YEAR, REPORTING_AREA_ZIP, SAMPLE_AREA_STATE_CODE, SAMPLE_AREA_COUNTY_CODE,
         SAMPLE_AREA_ZIP, LANDING_AREA_PLACE_CODE, LANDING_AREA_COUNTY_CODE, SAMPLE_AREA_PLACE_CODE, 
         GEAR_1, GEARNAME_1, GEAR_QTY_1, GEAR_FREQUENCY1, MIN_DEPTH1, MAX_DEPTH1, 
         OBS_STANDARD_SPECIES_CODE, OBS_STANDARD_SPECIES_NAME, TRIP_DAYS_FISHED, 
         LENGTH1, LENGTH_UNIT1, LENGTH_UNIT_CODE1, LENGTH_TYPE1, LENGTH_TYPE_CODE1, 
         LENGTH1_MM, OBS_WEIGHT, OBS_WEIGHT_KG, OBS_WEIGHT_UNIT, OBS_WEIGHT_UNIT_ID)

# create new filterable date value
com_tip_PR_1997_NEWDATE <- com_tip_PR_1997_skeleton %>%
  mutate(TEST_DATE = as.Date(ymd_hms(INTERVIEW_DATE)),
         FINAL_DATE = case_when(is.na(TEST_DATE) ~ INTERVIEW_DATE, 
                                TRUE ~ TEST_DATE))

com_tip_PR_1997_ORGANIZED <- com_tip_PR_1997_NEWDATE[,c(1,2,3,31, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30)]

save(com_tip_PR_1997_ORGANIZED,file="~/SEFSC-SFD-CFB-TIP-Compositions/data/dataframes/com_tip_PR_1997_ORGANIZED.Rda") # file is saved in data folder  

# Load HISTORICAL data 
PR_historical_97 <- read_csv("~/SEFSC-SFD-CFB-TIP-Compositions/data/raw/for_import_97.csv")

# Format dates to be mm/dd/yyyy 
pr_97 <- PR_historical_97 %>%
  # Format dates to be mm/dd/yyyy 
  mutate(INTDATE = as.Date(INTDATE, "%m/%d/%Y"))

save(pr_97,file="~/SEFSC-SFD-CFB-TIP-Compositions/data/dataframes/pr_97.Rda") # file is saved in data folder

```

#### Date Comparison

Each year must correct the date error in Oracle data caused by time field incorrectly being assigned due to daylight savings time.

```{r}
# DATE COMPARISON ####

load(file = "data/dataframes/pr_97.Rda")
load(file = "data/dataframes/com_tip_PR_1997_ORGANIZED.Rda")

# ORACLE unique dates and number of occurrences 
com_tip_PR_1997_UNIQUEDATES <- com_tip_PR_1997_ORGANIZED %>% 
  group_by(FINAL_DATE) %>% 
  summarize(count=n())
colnames(com_tip_PR_1997_UNIQUEDATES)[2] = "COUNT_ORACLE"

# somethings wrong with my rename function, idk what 
# com_tip_PR_1997_UNIQUEDATES_updated <- com_tip_PR_1997_UNIQUEDATES  |>
#   # rename("COUNT_ORACLE" = "count")
#  rename("count" = "COUNT_ORACLE")

# HISTORICAL unique dates and number of occurrences 
pr_97_historical_UNIQUEDATES <- pr_97 %>% 
  group_by(INTDATE) %>% 
  summarize(count=n())
colnames(pr_97_historical_UNIQUEDATES)[1] = "FINAL_DATE"
colnames(pr_97_historical_UNIQUEDATES)[2] = "COUNT_HISTORICAL"

# pr_97_historical_UNIQUEDATES_updated <- pr_97_historical_UNIQUEDATES %>%
#   rename(count = COUNT_HISTORICAL,
#           INTDATE = FINAL_DATE)

# combine two tables
unique_dates_merge_97 <- full_join(com_tip_PR_1997_UNIQUEDATES, pr_97_historical_UNIQUEDATES, by = 'FINAL_DATE')
# dates arent mismatching anymore???
# DATES ARE MISALIGNED FROM JAN 1 TO MARCH 31 AND OCT 26 TO DEC 31

# compare 
unique_dates_comparison_97 <- unique_dates_merge_97 %>%
  mutate(COMPARE = (COUNT_ORACLE - COUNT_HISTORICAL))


# change ORACLE dates so they align with HISTORICAL

com_tip_PR_1997_corrected_dates <- com_tip_PR_1997_ORGANIZED %>%
  mutate(NEWDATE = case_when(FINAL_DATE <= "1997-03-31" ~ (FINAL_DATE + days(1)),
                             TRUE ~ FINAL_DATE),
         NEWDATE = case_when(NEWDATE > "1997-10-25" ~ (NEWDATE + days(1)),
                             TRUE ~ NEWDATE)) 


save(com_tip_PR_1997_corrected_dates,file="data/dataframes/com_tip_PR_1997_corrected_dates.Rda") # file is saved in data folder  


# ORACLE unique dates and number of occurrences 
com_tip_PR_1997_UNIQUEDATES_2 <- com_tip_PR_1997_corrected_dates %>% 
  group_by(NEWDATE) %>% 
  summarize(count=n())
com_tip_PR_1997_UNIQUEDATES_updated_2 <- com_tip_PR_1997_UNIQUEDATES_2 %>%
  rename(COUNT_ORACLE = count)

# HISTORICAL unique dates and number of occurrences 
pr_97_historical_UNIQUEDATES <- pr_97 %>% 
  group_by(INTDATE) %>% 
  summarize(count=n())
pr_97_historical_UNIQUEDATES_updated_2 <- pr_97_historical_UNIQUEDATES %>%
  rename(COUNT_HISTORICAL = count,
         NEWDATE = INTDATE) 

# combine two tables
unique_dates_merge_97_2 <- full_join(com_tip_PR_1997_UNIQUEDATES_updated_2, pr_97_historical_UNIQUEDATES_updated_2, by = 'NEWDATE')

# compare 
unique_dates_comparison_97 <- unique_dates_merge_97_2 %>%
  mutate(COMPARE = (COUNT_ORACLE - COUNT_HISTORICAL))
# ORACLE IS MISSING 5 RECORDS ON 3/23 AND 3 ON 6/16 BUT MAKES UP FOR IT ON OTHER DATES 

write.csv(unique_dates_comparison_97, file = "data/CSVs/dates_comparison_97.csv", row.names = FALSE)
save(unique_dates_comparison_97,file="data/dataframes/dates_comparison_97.Rda") # file is saved in data fold

```
