# Load libraries ####
librarian::shelf(here, tidyverse, ROracle, keyring, dotenv)
# ctrl shift c for multiple line #

#?plot   #?command for help with command


# read in data ####
com_tip_PR_VI_20230627 <- 
  readRDS("~/SEFSC-SFD-CFB-TIP-Compositions/data/raw/com_tip_PR_VI_20230627.RDS")

#play around with plots
plot(com_tip_PR_VI_20230627$OBS_SPECIES_CODE)
plot(com_tip_PR_VI_20230627$OBS_SCIENTIFIC_NAME)

# EXPLORING DATA ####
summarise(com_tip_PR_VI_20230627)
head(com_tip_PR_VI_20230627)
view(com_tip_PR_VI_20230627)

# List of column names
colnames(com_tip_PR_VI_20230627, do.NULL = TRUE, prefix = "col")

# Finding unique data values in columns
unique(com_tip_PR_VI_20230627$REGIONNAME_1) 
#[1] "PUERTO RICO - USVI" NA                   "GULF" 
unique(com_tip_PR_VI_20230627$REGIONNAME_2)
#[1] NA                   "PUERTO RICO - USVI" "GULF" 
unique(com_tip_PR_VI_20230627$REGIONNAME_3)
#[1] NA                   "PUERTO RICO - USVI"
unique(com_tip_PR_VI_20230627$REGIONNAME_4)
#[1]NA                   "PUERTO RICO - USVI"
unique(com_tip_PR_VI_20230627$REGIONNAME_5)
#[1] NA
unique(com_tip_PR_VI_20230627$SAMPLE_SCIENTIFIC_NAME)
# 367 unique variables
unique(com_tip_PR_VI_20230627$OBS_SPECIES_CODE)

unique(com_tip_carsplob_small$AREA_2)
unique(com_tip_carsplob_small$LINE_LENGTH_4)

# Try to make the dataframe smaller
# Filter to just caribbean spiny lobster
com_tip_carsplob <- com_tip_PR_VI_20230627 %>% 
  filter(OBS_SPECIES_CODE %in% c(97648,618201010100, 7300, 901))

# summary(com_tip_small)
# head(com_tip_small)
com_tip_carsplob_small <- com_tip_carsplob %>%
  select(ID, STATE_LANDED, COUNTY_LANDED, LAND_GEAR_NAME, SAMPLE_STANDARD_SPECIES_NAME,
         SAMPLE_STANDARD_SPECIES_CODE, SAMPLE_SPECIES_SIZE, SAMPLE_CONDITION,
         SAMPLE_WEIGHT, SAMPLE_WEIGHT_UNIT, OBS_INTERVIEW_ID, OBS_GROUP, REC, LINE,
         OBS_ID, OBS_SAMPLE_ID, OBS_SPECIES_CODE, OBS_AGENCY_SPC_NAME,
         OBS_STANDARD_SPECIES_CODE, OBS_STANDARD_SPECIES_NAME, OBS_SCIENTIFIC_NAME,
         QUANTITY, LENGTH1, LENGTH_UNIT1, LENGTH_UNIT_CODE1,    LENGTH_TYPE1,
         LENGTH_TYPE_CODE1, LENGTH1_MM, LENGTH2, LENGTH_UNIT2, LENGTH_UNIT_CODE2,
         LENGTH_TYPE2, LENGTH_TYPE_CODE2, LENGTH2_MM, LENGTH3, LENGTH_UNIT3,
         LENGTH_UNIT_CODE3, LENGTH_TYPE3, LENGTH_TYPE_CODE3, LENGTH3_MM, EXACT_LENGTH,
         START_LENGTH, END_LENGTH, LENGTH_INCREMENT, UNUSUAL_LENGTH, SEX, SEX_NAME,
         SECONDARY_SEX, MATURITY_STAGE, TAG1, SAMPLE_TYPE_1, DESTINATION_1, TAG2,
         SAMPLE_TYPE_2, DESTINATION_2, TAG3, SAMPLE_TYPE3, DESTINATION_3, OBS_WEIGHT,
         OBS_WEIGHT_UNIT, OBS_WEIGHT_UNIT_ID, OBS_WEIGHT_KG, OBS_GRADE, OBS_SPECIES_SIZE,
         OBS_SPECIES_SIZE_CODE, CONDITION_TYPE, SAMPLE_METHOD, AGE, AGE_STATUS,
         OBS_COMMENT, OBS_CREATED_BY_USER_ID, OBS_CREATED_DATE, OBS_MODIFIED_BY,
         OBS_MODIFIED_DATE, OBS_REPLICATE, OBS_OLD_SAMPLE_ID, EFFORT_INTERVIEW_ID,
         NUMBER_OF_EFFORT_RECORDS, GEAR_1,  GEARNAME_1, STANDARDGEAR_1,
         STANDARDGEARNAME_1, GEAR_QTY_1, GEAR_FREQUENCY1, NUMBER_OF_GEAR_1,
         LINE_LENGTH_1, SOAK_TIME_1,  REGIONNAME_1, AREA_1, AREANAME_1,
         STANDARDAREA_1, STANDARDAREANAME_1, MIN_DEPTH1, MAX_DEPTH1, EFF_CREATED_DATE1,
         EFF_MODIFIED_DATE1, GEAR_2, GEARNAME_2, STANDARDGEAR_2, STANDARDGEARNAME_2,
         GEAR_QTY_2, GEAR_FREQUENCY2, NUMBER_OF_GEAR_2, LINE_LENGTH_2, SOAK_TIME_2,
         REGIONNAME_2, AREA_2, AREANAME_2, STANDARDAREA_2, STANDARDAREANAME_2, MIN_DEPTH2,
         MAX_DEPTH2, EFF_CREATED_DATE2, EFF_MODIFIED_DATE2, GEAR_3, GEARNAME_3,
         STANDARDGEAR_3, STANDARDGEARNAME_3, GEAR_QTY_3, GEAR_FREQUENCY3, NUMBER_OF_GEAR_3,
         LINE_LENGTH_3, SOAK_TIME_3, REGIONNAME_3, AREA_3, AREANAME_3, STANDARDAREA_3,
         STANDARDAREANAME_3, MIN_DEPTH3, MAX_DEPTH3, EFF_CREATED_DATE3, EFF_MODIFIED_DATE3,
         GEAR_4, GEARNAME_4, STANDARDGEAR_4,STANDARDGEARNAME_4, GEAR_QTY_4, 
         GEAR_FREQUENCY4, NUMBER_OF_GEAR_4, LINE_LENGTH_4, SOAK_TIME_4, REGIONNAME_4, 
         AREA_4, AREANAME_4, STANDARDAREA_4,STANDARDAREANAME_4, MIN_DEPTH4, MAX_DEPTH4,
         EFF_CREATED_DATE4, EFF_MODIFIED_DATE4, INTERVIEW_UNIQUE, 
         EFFORT_UNIQUE, LANDING_UNIQUE, SAMPLE_UNIQUE,OBSERVATION_UNIQUE)


#write.csv(com_tip_PR_VI_20230627, here("data", "raw", paste0("com_tip_prvi_", 
 # format(Sys.Date(), "%Y%m%d"), ".csv")), row.names = FALSE)
